theme: minima
title: "keltan's blog"
description: "keltan's thoughts and explorations"
author: keltan
show_downloads: false
domain: keltan.studio
url: https://keltan.studio
baseurl: ""
plugins:
  - jekyll-feed
  - jekyll-sitemap
