theme: minima
title: "keltan's Repository"
description: "The repository for my website"
author: keltan
show_downloads: false
google_analytics: # Optional - leave empty for now
plugins:
  - jekyll-feed
  - jekyll-sitemap
